language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libboost1.52-all-dev
    - perl
    - gcc-4.5
    - g++-4.5
script: configure && make
